(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/goods/bd-service"],{2210:function(e,t,n){"use strict";(function(e){Object.defineProperty(t,"__esModule",{value:!0}),t.default=void 0;var r=n("7736");function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function c(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}var i={name:"bd-service",props:{name:String,url:String},computed:c({},(0,r.mapState)({mall:function(e){return e.mallConfig.mall}})),methods:{router:function(t){e.navigateTo({url:t})},makePhoneCall:function(){this.mall.setting.contact_tel&&e.makePhoneCall({phoneNumber:this.mall.setting.contact_tel})}}};t.default=i}).call(this,n("d2c1")["default"])},"41ecc":function(e,t,n){"use strict";n("8394")},8394:function(e,t,n){},"861b":function(e,t,n){"use strict";n.r(t);var r=n("d777"),o=n("dac6");for(var c in o)["default"].indexOf(c)<0&&function(e){n.d(t,e,(function(){return o[e]}))}(c);n("41ecc");var a=n("5d22"),i=Object(a["a"])(o["default"],r["a"],r["b"],!1,null,"2af37e3b",null);t["default"]=i.exports},d777:function(e,t,n){"use strict";n.d(t,"a",(function(){return r})),n.d(t,"b",(function(){return o}));var r=function(){var e=this,t=e.$createElement,n=(e._self._c,encodeURIComponent(e.mall.setting.web_service_url));e.$mp.data=Object.assign({},{$root:{m0:n}})},o=[]},dac6:function(e,t,n){"use strict";n.r(t);var r=n("2210"),o=n.n(r);for(var c in r)["default"].indexOf(c)<0&&function(e){n.d(t,e,(function(){return r[e]}))}(c);t["default"]=o.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/goods/bd-service-create-component',
    {
        'components/page-component/goods/bd-service-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('d2c1')['createComponent'](__webpack_require__("861b"))
        })
    },
    [['components/page-component/goods/bd-service-create-component']]
]);                
