(global["webpackJsonp"]=global["webpackJsonp"]||[]).push([["components/page-component/goods/bd-xbc"],{"14bf":function(t,n,r){"use strict";r("ab2e")},8639:function(t,n,r){"use strict";r.r(n);var e=r("8d56"),a=r("f9ad");for(var i in a)["default"].indexOf(i)<0&&function(t){r.d(n,t,(function(){return a[t]}))}(i);r("14bf");var o=r("5d22"),u=Object(o["a"])(a["default"],e["a"],e["b"],!1,null,"a4bff87c",null);n["default"]=u.exports},"8d56":function(t,n,r){"use strict";r.d(n,"a",(function(){return e})),r.d(n,"b",(function(){return a}));var e=function(){var t=this,n=t.$createElement;t._self._c;t._isMounted||(t.e0=function(n){t.show=!1},t.e1=function(n){t.show=!1})},a=[]},ab2e:function(t,n,r){},c3d8:function(t,n,r){"use strict";Object.defineProperty(n,"__esModule",{value:!0}),n.default=void 0;var e=function(){return r.e("components/basic-component/u-popup/u-popup").then(r.bind(null,"d55a"))},a={name:"bd-xbc",props:{attrGroups:Array,services:Array,attrList:Array,guaranteeTitle:String,guaranteePic:String,param_content:{type:Array,default:function(){return[]}},param_name:String,type:String,goodsStock:Number,coAttr:{type:[Number,Boolean],default:1}},data:function(){return{attrStr:"请选择规格",serviceStr:"",paramStr:"",newAttrGroups:[],attrCount:[],attrName:"",pictureList:[],show:!1,isShow:""}},watch:{attrList:{deep:!0,immediate:!0,handler:function(t){var n="";this.$validation.isEmpty(t)?n="请选择规格":t.forEach((function(t){n+="".concat(t.attr_group_name,":").concat(t.attr_name," ")})),this.attrStr=n}},services:{immediate:!0,handler:function(){var t="";this.$validation.isEmpty(this.services)||this.services.forEach((function(n){t+="".concat(n.name," · ")})),t=t.substring(0,t.lastIndexOf(" · ")+1),this.serviceStr=t}},attrGroups:{immediate:!0,handler:function(t){var n=this;this.newAttrGroups=[],this.pictureList=[],this.attrCount=0,this.attrName="",t&&t.length>0&&t.forEach((function(t,r){n.attrName||(n.attrName=t.attr_group_name,t.attr_list.forEach((function(){n.attrCount+=1}))),0===r&&t.attr_list.forEach((function(t){n.newAttrGroups.length<3&&n.newAttrGroups.push(t),t.pic_url&&n.pictureList.length<5&&n.pictureList.push(t.pic_url)}))}))}},param_content:{immediate:!0,handler:function(t){var n="";this.$validation.isEmpty(t)||t.forEach((function(t){n+="".concat(t.key," ")})),n=n.substring(0,n.lastIndexOf(" ")+1),this.paramStr=n}}},components:{uPopup:e},methods:{open:function(t){"attr"===t?this.$emit("openAttr"):(this.show=!0,this.isShow=t)}}};n.default=a},f9ad:function(t,n,r){"use strict";r.r(n);var e=r("c3d8"),a=r.n(e);for(var i in e)["default"].indexOf(i)<0&&function(t){r.d(n,t,(function(){return e[t]}))}(i);n["default"]=a.a}}]);
;(global["webpackJsonp"] = global["webpackJsonp"] || []).push([
    'components/page-component/goods/bd-xbc-create-component',
    {
        'components/page-component/goods/bd-xbc-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('d2c1')['createComponent'](__webpack_require__("8639"))
        })
    },
    [['components/page-component/goods/bd-xbc-create-component']]
]);                
